services:
  - type: web
    name: node-app
    runtime: node
    plan: free        # or starter / standard depending on your plan
    region: singapore    # optional; can be oregon, frankfurt, singapore, etc.
    envVars:
      - key: DB_USER
        value: shiva-prod
      - key: DB_PASSWORD
        value: shiva-prod456mern
      - key: LOCATOR_API_KEY
        value: c741ef603692da21cfafde367a081786
      - key: JWT_KEY
        value: shivaisamernstackdeveloper
    buildCommand: npm ci
    startCommand: node app.js

